# Generated by Django 5.0.14 on 2026-08-02 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('PAGEVIEW', 'Pageview'), ('INQUIRY_SUBMISSION', 'Inquiry Submission'), ('LOGIN_EVENT', 'Login Event')], max_length=30)),
                ('path', models.CharField(blank=True, max_length=255, null=True)),
                ('details', models.JSONField(blank=True, help_text='Additional key-value metadata for the event.', null=True)),
                ('ip_hash', models.CharField(blank=True, help_text='Hashed IP address for privacy-compliant distinct user counts.', max_length=64, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
