# Generated by Django 5.0.14 on 2026-08-02 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="Config key (e.g. 'site_title', 'contact_email')", max_length=100, unique=True)),
                ('value', models.TextField()),
                ('description', models.TextField(blank=True, help_text='Brief description explaining what this setting changes.')),
                ('group', models.CharField(choices=[('GENERAL', 'General'), ('SEO', 'SEO'), ('CONTACT', 'Contact Details'), ('SOCIAL', 'Social Links')], default='GENERAL', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['group', 'key'],
            },
        ),
    ]
