# Generated by Django 5.1.15 on 2026-08-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tech_stack',
            field=models.CharField(blank=True, help_text='Comma-separated technologies used, e.g. React, Next.js, Django', max_length=500, null=True),
        ),
    ]
