# Generated by Django 5.0.14 on 2026-08-02 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PricingTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('cost', models.CharField(help_text="e.g. '$499', '$1200', 'Custom'", max_length=50)),
                ('billing_cycle', models.CharField(default='month', help_text="e.g. 'month', 'year', 'project'", max_length=50)),
                ('short_description', models.TextField()),
                ('features', models.JSONField(default=list, help_text="A list of string features, e.g. ['Up to 10 users', 'API Access']")),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PricingInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(blank=True, max_length=150, null=True)),
                ('estimated_budget', models.CharField(blank=True, max_length=100, null=True)),
                ('requirements', models.TextField()),
                ('custom_configuration', models.JSONField(blank=True, default=dict, help_text='Stores calculator custom config state (sliders, checked features).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pricing_tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='pricing.pricingtier')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
